config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
    }

  scope module: :public do
    resources :users, only: [:show, :edit] do
      member do
        get :posts
      end

      collection do
        get :unsubscribe
        patch :withdraw
      end
    end

    resources :posts
    
    root to: "homes#top"
    get 'homes/about'

    #　ゲストログイン
    devise_scope :user do
       post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  
  # geocoder関係
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_one_attached :profile_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #　プロフィールイメージフォント調整  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default_profile.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default_profile.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # ゲストログイン用メソッド
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.user_name = "ゲストユーザー"
      user.profile = <<~TEXT
        このアカウントはゲストユーザー用アカウントです。
        どなたでもご利用できます。
        ゲストアカウントの編集・削除はできません。
      TEXT
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :profile, :profile_image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:user_name, :profile, :profile_image])
  end

  def record_not_found
    redirect_to posts_path, alert: "投稿は削除済みです"
  end

   # サインイン後の遷移先指定
  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # プロフィール画像とデフォルト未設定の場合のデフォルト画像設定
  def profile_image_for(user, size: [150, 150])
    if user.profile_image.attached?
      image_tag user.profile_image.variant(resize_to_limit: size)
    else
      image_tag 'default_profile.jpg', size: "#{size[0]}x#{size[1]}"
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/about.html.erb
<div class="container d-flex justify-content-center align-items-center" style="height: 90vh;">
  <div class="row">
    <div class="col-12 mb-5">
      <h5>このサイトは位置情報を投稿するサイトです。</h5>
      <h5 class="mt-4">その日起きた出来事を地図上で確認したり、</h5>
      <h5 class="mt-4">自身で見知った出来事を投稿することができます。</h5>
      <h5 class="mt-4">また、過去の出来事を遡って確認することができます。</h5>
    </div>
    <div class="col-10 mt-2 d-flex justify-content-center">
      <h5>投稿一覧ページへのリンク</h5>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container d-flex justify-content-center align-items-center" style="height: 90vh;">
  <div class="row">
    <div class="col-12 mb-5">
      <h5>ようこそWorldNavigationへ！</h5>
      <h5 class="mt-4">このサイトは、位置情報投稿のECサイトになります。</h5>
      <h5 class="mt-4">アカウントがない方も記事の閲覧はできますが、</h5>
      <h5 class="mt-4">記事の投稿には会員登録が必要になります。</h5>
    </div>
    <div class="mt-5">
      <h5>地図機能実装予定</h5>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NavigationMappsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navigation-bar" %>
    <% if flash[:notice] %>
      <div class="alert alert-success text-center mb-0">
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger text-center mb-0">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
    <%= render "shared/footer" %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-jpostal-ja@2.14.45/jquery.jpostal.min.js"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-dark text-white text-center text-md-start mt-5 ">
  <div class="container-fluid p-4" style="max-width: 1000px;">
    <div class="row">

      <div class="col-md-4 mb-4">
        <h6 class="text-uppercase fw-bold">サービス</h6>
        <ul class="list-unstyled">
          <li><%= link_to "このサイトについて", homes_about_path, class:"text-white" %></li>
          <li><%= link_to "投稿一覧", posts_path, class:"text-white" %></li>
        </ul>
      </div>

      <div class="col-md-4 mb-4">
        <h6 class="text-uppercase fw-bold">サポート</h6>
        <ul class="list-unstyled">
          <li>お問い合わせ</li>
          <li>FAQ</li>
        </ul>
      </div>

      <div class="col-md-4 mb-4">
        <h6 class="text-uppercase fw-bold">フォロー</h6>
        <a href="#" class="me-2"><i class="fab fa-twitter"></i></a>
        <a href="#" class="me-2"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
      </div>

    </div>
  </div>

  <div class="text-center p-3 bg-dark text-white border-top">
    © <%= Time.current.year %> Navigation Map. All rights reserved.
  </div>
</footer>

app/views/shared/_navigation-bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container", style="max-width: 1000px;">

    <%= link_to posts_path, class: "navbar-brand text-secondary logo-font" do %>
      <i class="fa-solid fa-earth-americas me-2"></i>
      Navigation Map
    <% end %>


    <!-- レスポンシブ対応ハンバーガーメニュー -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end mr-5" id="navbarNav">
      <ul class="navbar-nav ms-auto ">

        <li class="nav-item mr-4">
          <%= link_to "このサイトについて", homes_about_path, class: "nav-link text-secondary" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item mr-4">
            <%= link_to "新規投稿", new_post_path, class: "nav-link text-secondary " %>
          </li>
          <li class="nav-item mr-4">
            <%= link_to "マイページ", user_path(current_user), class: "nav-link text-secondary " %>
          </li>
          <li class="nav-item navbar-nav ms-auto">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link text-secondary" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-secondary mr-4" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link text-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link text-secondary" %>
          </li>
        <% end %>

      </ul>
    </div>

  </div>
</nav>